### ISSUE TITLE
[Suggestion] Font variants adapted for programming

### ISSUE THREAD

**Issue by omixann** [ClintGoss/Kurinto#11]
There are some contrarians (e.g: me at least) out there who really want to try using proportional fonts in a programming environment. The major problem with proportional fonts is that the spacing and symbols are optimized for the most common use case: human texts. I think it might be interesting to provide alternative versions of those (symbols, spaces, 0/O, 1/I/L/l) for that specific use case. An example of a proportional, dev-oriented font is [Input](https://input.djr.com/info).

Why I'd want this font specifically to support it? Two main reasons: it has an impressive Unicode coverage and it has a semi-serif variant which I particularly appreciate.

**Comment by ClintGoss** [comment]
I spent quite a bit to time exploring the opportunities and issues relating to programming fonts. Some of the major issues are the most mundane - line height seems to be one of *the* most important issues (for me, at least) in terms of readability in a typical character-oriented display. I did experiment with *limited* proportionality - using double-wide for the obvious Kanji and Balinese scripts and 1.5-wide characters for many characters that could really use expansion.

Honestly, the thing that discouraged me is that most of my personal friends who are life-long programmers gave me the _"Fonts? Who Cares?"_ reaction. I suspect that, like background noise in a restaurant, we may not be aware of it, but it does have a significant impact on our productivity and stress-level. However, portability of code across many different programming environments is part of the landscape, and writing code in a proportional font environment would render as so "messed up" formatting wise when it eventually winds up in a fixed-pitch environment that I fear it may be counter-productive.

The [Input] font is cool ... thanks for that ...

**Comment by omixann** [comment]
I fully agree that its usage would be really, _really_ niche. Even Plan 9 users I know just use monospaced fonts. However, I think it's also a chicken-and-egg problem where no proportional fonts are good for programming, so nobody programs with those.

Ultimately I fully understand it's not enticing at all to put effort on a feature only a handful will appreciate, as much as I'd like it.
